---
apiVersion: v1
kind: Service
metadata:
  name: example-postgresql-exporter
  namespace: demo
  labels:
    name: example-postgresql-exporter
    app: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9187
      protocol: TCP
      name: metrics
  selector:
    name: example-postgresql-exporter