---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-postgresql
  namespace: demo
  labels:
    name: example-postgresql
    app: postgresql
spec:
  serviceName: example-postgresql
  selector:
    matchLabels:
      name: example-postgresql
      app: postgresql
  template:
    metadata:
      name: example-postgresql
      labels:
        name: example-postgresql
        app: postgresql
    spec:      
      initContainers:
      - name: change-permission
        image: postgres:10.12
        command: ["/bin/bash", "-c"]
        args: ["chown -R 999:999 /var/lib/postgresql/data/pgdata"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data/pgdata
          subPath: postgresql-db
      containers:
        - name: example-postgresql
          image: postgres:10.12
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres  
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POD_IP
              valueFrom: { fieldRef: { fieldPath: status.podIP } }
          ports:
            - name: postgresql
              containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - exec pg_isready -h $POD_IP
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data/pgdata
            subPath: postgresql-db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"