apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: example-postgresql-exporter
  name: example-postgresql
  namespace: demo
spec:
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
  - interval: 5s
    port: metrics
  selector:
    matchLabels:
      name: example-postgresql-exporter