apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-redis
  name: demo-redis
  namespace: demo
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: demo-redis